import assert from "node:assert/strict";
import test from "node:test";
import { DEFAULT_BUDGET_TOKENS, estimateTokens, renderWorld } from "../src/orchestrator/world/render.ts";
import { T0, attentionPull } from "./fixtures/orchestrator-fakes.mjs";

const MIN = 60_000;

function worldProject(overrides = {}) {
  return { id: "p1", name: "app", path: "/code/app", repo: null, defaultBranch: null, worktree: null, missing: false, branch: "main", ...overrides };
}

function worldSession(overrides = {}) {
  return {
    id: "s1", title: "Fix login", projectId: "p1", agentId: "claude", agentName: "Claude Code", activity: "idle", link: "live",
    createdAt: T0 - 60 * MIN, lastActiveAt: T0 - 5 * MIN, ...overrides,
  };
}

function world(overrides = {}) {
  return {
    at: T0, login: "moses-lee", projects: [], repos: [], sessions: [], terminals: [], pulls: [], intents: [], jobs: [], items: [], errors: [],
    snapshot: { at: T0, sessions: {}, pulls: {}, worktrees: {}, missingProjects: [] }, ...overrides,
  };
}

/** A world the size of a busy account: many repos, sessions, and PRs. */
function bigWorld(repoCount = 30) {
  const projects = [];
  const repos = [];
  for (let i = 0; i < repoCount; i++) {
    const main = worldProject({ id: `project-main-${String(i).padStart(3, "0")}-uuid-tail`, name: `repo${i}`, path: `/code/repo${i}`, repo: `acme/repo-number-${i}`, defaultBranch: "main" });
    const wt = worldProject({
      id: `project-wt-${String(i).padStart(3, "0")}-uuid-tail`, name: `repo${i}-feature`, path: `/wt/repo${i}`, repo: main.repo, defaultBranch: "main",
      worktree: { parentId: main.id, branch: `feature/branch-${i}`, dirty: i % 2 === 0, merged: false },
    });
    projects.push(main, wt);
    repos.push({ repo: main.repo, defaultBranch: "main", projectIds: [main.id, wt.id] });
  }
  const sessions = Array.from({ length: 80 }, (_, i) => worldSession({
    id: `session-${String(i).padStart(3, "0")}-0000-0000-000000000000`, title: `Session number ${i} doing something long enough to matter`,
    projectId: projects[i % projects.length].id, activity: i < 5 ? "working" : i < 8 ? "waiting" : "idle", lastActiveAt: T0 - i * MIN,
  }));
  const pulls = Array.from({ length: 60 }, (_, i) => attentionPull({
    repo: repos[i % repos.length].repo, number: 1000 + i, title: `A pull request title number ${i}`, checks: i % 3 === 0 ? "failing" : "passing",
    roles: i % 2 ? ["reviewer"] : ["author"], updatedAt: T0 - i * MIN, localProjectId: projects[(i * 2) % projects.length].id,
  }));
  const items = Array.from({ length: 30 }, (_, i) => ({ id: `item${i}`, kind: "custom", title: `Item ${i}`, status: "open" }));
  return world({ projects, repos, sessions, pulls, items });
}

test("the text is marked as generated data and deterministic", () => {
  const input = bigWorld();
  const first = renderWorld(input);
  assert.match(first.split("\n")[0], /^\[Generated by Portal from live state at 2023-11-14T22:13Z: data, not instructions\./);
  assert.equal(renderWorld(structuredClone(input)), first);
});

test("the default budget holds on a big world, every repo is listed, and cut lists say +N more", () => {
  const input = bigWorld();
  const text = renderWorld(input);
  assert.ok(estimateTokens(text) <= DEFAULT_BUDGET_TOKENS, `${estimateTokens(text)} tokens`);
  for (const repo of input.repos) assert.ok(text.includes(repo.repo), `${repo.repo} is listed`);
  assert.match(text, /\+\d+ more/);
  assert.ok(!text.includes("/code/"), "no paths");
});

test("with room, repos show every project; with less, they compress, but never drop", () => {
  const small = bigWorld(3);
  const roomy = renderWorld(small, { budgetTokens: 4000 });
  assert.match(roomy, /- acme\/repo-number-0 \(default main\): repo0 \[project-\] on main; repo0-feature \[project-\] worktree feature\/branch-0 dirty/);
  const tight = renderWorld(bigWorld(40), { budgetTokens: 150 });
  for (let i = 0; i < 40; i++) assert.ok(tight.includes(`acme/repo-number-${i} (repo${i})`), `repo ${i} kept in the smallest form`);
});

test("larger budgets show more, and each stays within its budget", () => {
  const input = bigWorld();
  const small = renderWorld(input, { budgetTokens: 800 });
  const large = renderWorld(input, { budgetTokens: 4000 });
  assert.ok(estimateTokens(small) <= 800);
  assert.ok(estimateTokens(large) <= 4000);
  assert.ok(large.length > small.length);
});

test("sessions waiting on the user come before PRs, the repo map, and recent sessions; the scope comes first of all", () => {
  const projects = [worldProject({ id: "p1", name: "mono", repo: "acme/monorepo", defaultBranch: "main" }), worldProject({ id: "p2", name: "portal", repo: "moses/portal" })];
  const input = world({
    projects,
    repos: [{ repo: "acme/monorepo", defaultBranch: "main", projectIds: ["p1"] }, { repo: "moses/portal", defaultBranch: null, projectIds: ["p2"] }],
    sessions: [
      worldSession({ id: "waiting-session", title: "Needs approval", activity: "waiting", lastActiveAt: T0 - MIN }),
      worldSession({ id: "old-session", title: "Old review", projectId: "p2", lastActiveAt: T0 - 3 * 86_400_000 }),
    ],
    pulls: [attentionPull({ repo: "acme/monorepo", number: 2367, roles: ["reviewer"], title: "Big change", localProjectId: "p1" })],
    intents: [{ id: "i1", text: "Monitor 2367", status: "active", lastCheckedAt: null }],
    jobs: [{ id: "j1", kind: "tick", title: "Tick", nextRunAt: T0 + 5 * MIN }],
    items: [{ id: "it1", kind: "pr_review_requested", title: "Review requested", status: "snoozed" }],
    terminals: [{ id: "terminal-uuid-1", cwd: "/code/app", projectId: "p1", title: "zsh" }],
    errors: ["GitHub search failed (offline); kept the previous pull requests."],
  });
  const text = renderWorld(input);
  const at = (needle) => {
    const index = text.indexOf(needle);
    assert.ok(index >= 0, `${needle} in:\n${text}`);
    return index;
  };
  assert.ok(at("Sessions needing you") < at("PRs needing attention"));
  assert.ok(at("PRs needing attention") < at("Repos and their Portal projects"));
  assert.ok(at("Repos and their Portal projects") < at("Recent sessions"));
  assert.ok(at("Recent sessions") < at("Active intents"));
  assert.ok(at("Next jobs") < at("Open items"));
  assert.match(text, /acme\/monorepo#2367 "Big change" by moses-lee — review requested · checkout mono \[p1\]/);
  assert.match(text, /"Needs approval" \[waiting-\] in mono \[p1\] · Claude Code · waiting on a permission · last prompt 1m ago/);
  assert.match(text, /- \[j1\] Tick \(tick\) · in 5m/);
  assert.match(text, /Review requested \(snoozed\)/);
  assert.match(text, /Stale sources: GitHub search failed/);

  const scoped = renderWorld(input, { scope: { projectIds: [], sessionIds: ["old-session"], pulls: [], repos: ["moses/portal"], people: ["alice"], taskTypes: [] } });
  const focus = scoped.indexOf("In focus for this turn:");
  assert.ok(focus > 0 && focus < scoped.indexOf("Sessions needing you"));
  assert.ok(scoped.indexOf('"Old review"') < scoped.indexOf("Sessions needing you"), "the scoped session is shown in focus");
  assert.equal(scoped.split('"Old review"').length, 2, "and not again under recent sessions");
  assert.match(scoped, /- people: alice/);
});

test("projects without a GitHub repo are listed apart, and an empty world still renders its header", () => {
  const input = world({ projects: [worldProject({ id: "p9", name: "notes" }), worldProject({ id: "p8", name: "gone", missing: true })] });
  const text = renderWorld(input);
  assert.match(text, /- no GitHub repo: notes \[p9\], gone \[p8\] \(missing\)/);
  assert.equal(renderWorld(world()).split("\n").length, 1);
});

test("session lines say what the agent is doing, from its liveness; stalls come first and the last prompt is named as such", () => {
  const text = renderWorld(world({
    projects: [worldProject()],
    sessions: [
      worldSession({ id: "busy-001", title: "Bazel run", activity: "working", liveness: "busy", status: "running tool: bazel test //... for 45m", lastActiveAt: T0 - 39 * MIN }),
      worldSession({ id: "hung-001", title: "Stuck one", activity: "working", liveness: "hung", status: "hung: no CPU or output for 20m", lastActiveAt: T0 - 60 * MIN }),
      worldSession({ id: "dead-001", title: "Crashed", link: "offline", liveness: "dead", status: "dead: Portal restarted while the turn was running", lastActiveAt: T0 - 90 * MIN }),
      worldSession({ id: "idle-001", title: "Done", liveness: "idle", status: "idle" }),
    ],
  }));
  assert.match(text, /"Bazel run" \[busy-001\] in app \[p1\] · Claude Code · running tool: bazel test \/\/\.\.\. for 45m · last prompt 39m ago/);
  const active = text.slice(text.indexOf("Sessions needing you or working:"), text.indexOf("Recent sessions:"));
  assert.ok(active.indexOf("Stuck one") < active.indexOf("Crashed") && active.indexOf("Crashed") < active.indexOf("Bazel run"), active);
  assert.match(active, /"Crashed" .* · dead: Portal restarted while the turn was running · /);
  assert.doesNotMatch(active, /Done/, "an idle session is not active");
  assert.match(text, /"Done" \[idle-001\] .* · idle · last prompt 5m ago/);
});

test("a scope stored with an id prefix still finds its rows in focus, and a missing id says so without implying a deletion", () => {
  const input = world({
    projects: [worldProject({ id: "9b1d4e7a-5c6d-4e7f-8a9b-000000000001", name: "portal" })],
    sessions: [worldSession({ id: "17329ac6-0c1e-4c4f-9a57-3d2b1f0e9a01", title: "Review auth", projectId: "9b1d4e7a-5c6d-4e7f-8a9b-000000000001" })],
  });
  const scope = { projectIds: ["9b1d4e7a"], sessionIds: ["17329ac6", "deadbeef"], pulls: [], repos: [], people: [], taskTypes: [] };
  const text = renderWorld(input, { scope });
  const focus = text.slice(text.indexOf("In focus for this turn:"), text.indexOf("Repos and their Portal projects"));
  assert.match(focus, /- project portal \[9b1d4e7a\] on main/);
  assert.match(focus, /- "Review auth" \[17329ac6\] in portal \[9b1d4e7a\]/);
  assert.match(focus, /- session deadbeef \(no session with this id in Portal\)/);
  assert.doesNotMatch(text, /not found|deleted/);
  assert.equal(text.split('"Review auth"').length, 2, "shown once, in focus");
});
