/**
 * Curated memory: entities (the global scope, people, repos, projects, sessions, task types), each
 * with a summary, and records that hold one claim each with its provenance. Records are never
 * overwritten: a change supersedes, a retraction archives with lineage, and every change writes a
 * revision. Observed or inferred claims arrive as `proposed` (the **inbox**) and become `active`
 * only when the user (or, in phase 3, the consolidator) approves them; claims the user states apply
 * at once. Among active records, `(entityId, key)` is unique, so a contradiction is detectable.
 *
 * `CORE.md` is generated from pinned directives plus one index line per entity and injected into
 * every turn, frozen for that turn; the rest is retrieved by scope (the repo, project, or session a
 * turn is about, the task type, the people named) and by full-text search.
 *
 * HTTP surface:
 *   GET    /api/portal/memory/entities                    { entities }
 *   GET    /api/portal/memory/entities/:id                { entity, records }
 *   GET    /api/portal/memory/records?status=&entityId=&type=&q=   { records }
 *   POST   /api/portal/memory/records                     body MemoryRecordInput -> { record }   (the user adds: user_stated)
 *   PATCH  /api/portal/memory/records/:id                 body MemoryRecordPatch -> { record }  (a user edit supersedes)
 *   POST   /api/portal/memory/records/:id/approve         -> { record }     (inbox → active, user_confirmed)
 *   POST   /api/portal/memory/records/:id/reject          body { reason? } -> { record }
 *   POST   /api/portal/memory/records/:id/forget          body { reason? } -> { record }
 *   GET    /api/portal/memory/revisions?recordId=&entityId=&before=&limit=   { revisions }
 *   GET    /api/portal/memory/core                        CoreDocument
 * Live: `{ type: "memory", recordIds }` after any change; the inbox count rides on `status`.
 */
import type { PullRef, Scope } from "./orchestrator.ts";

export type EntityType = "global" | "person" | "repo" | "project" | "session" | "task_type";
export const entityTypes: readonly EntityType[] = ["global", "person", "repo", "project", "session", "task_type"];

export type MemoryEntity = {
  id: string;
  type: EntityType;
  /**
   * The natural key: "global"; a GitHub login; "owner/name"; a Portal project or session id; a
   * task-type slug such as "code-review". Unique per type.
   */
  key: string;
  /** Display name: a person's name or login, a project's name, a session's title. */
  name: string;
  /** A short Markdown summary of what the records say, regenerated by curation. */
  summary: string;
  /** Active records, for the browser's list. */
  activeRecords: number;
  createdAt: number;
  updatedAt: number;
};

export type RecordType = "preference" | "feedback" | "convention" | "fact" | "procedure" | "reference";
export const recordTypes: readonly RecordType[] = ["preference", "feedback", "convention", "fact", "procedure", "reference"];

export type RecordStatus = "active" | "proposed" | "superseded" | "expired" | "archived" | "rejected";

/**
 * How much the claim is the user's word: stated by them, confirmed by them (an approved proposal),
 * observed by the agent in their work, or inferred. Only user_stated and user_confirmed records can
 * be pinned into CORE.md as directives: text from transcripts, PRs, or tool output never can.
 */
export type Authority = "user_stated" | "user_confirmed" | "observed" | "inferred";

export type RecordSource = {
  kind: "message" | "session" | "pull" | "import" | "tool" | "consolidator" | "ui";
  threadId?: string;
  messageId?: string;
  sessionId?: string;
  pull?: PullRef;
  runId?: string;
  url?: string;
  /** The words the claim rests on, verbatim and short. */
  quote?: string;
};

export type MemoryRecord = {
  id: string;
  entityId: string;
  type: RecordType;
  /** A stable slug within the entity, e.g. "review-style" or "preferred-model.code-review". */
  key: string;
  /** The claim, in Markdown; one claim per record. */
  body: string;
  status: RecordStatus;
  /** Where the claim applies beyond its entity (a convention for two repos, a preference for one task type). */
  scope: Scope;
  authority: Authority;
  source: RecordSource;
  /** 0..1: how far to rely on it. */
  trust: number;
  /** Always in CORE.md as a directive. */
  pinned: boolean;
  /** When the claim should be re-confirmed; past it the consolidator lists it for review. */
  reviewBy: number | null;
  /** The record this one replaced. */
  supersedes: string | null;
  supersededBy: string | null;
  createdAt: number;
  updatedAt: number;
};

/** What the user or a tool hands in to create a record; the entity is named by type and key and created when missing. */
export type MemoryRecordInput = {
  entity: { type: EntityType; key: string; name?: string };
  type: RecordType;
  key: string;
  body: string;
  scope?: Partial<Scope>;
  pinned?: boolean;
  reviewBy?: number | null;
  source?: RecordSource;
};

/** A user edit from the browser. Changing `body` supersedes the record with a new one. */
export type MemoryRecordPatch = Partial<Pick<MemoryRecord, "body" | "pinned" | "reviewBy" | "type">> & { status?: "archived" };

export type MemoryRevisionAction =
  | "created" | "updated" | "approved" | "rejected" | "superseded" | "expired" | "archived" | "forgotten" | "restored" | "imported";

export type MemoryRevision = {
  id: number;
  recordId: string | null;
  entityId: string | null;
  at: number;
  actor: "user" | "agent" | "consolidator" | "system";
  action: MemoryRevisionAction;
  before: MemoryRecord | null;
  after: MemoryRecord | null;
  reason: string | null;
  runId: string | null;
};

export type CoreDocument = { text: string; generatedAt: number; tokens: number };
